TheoremTalk/urls.py
from django.contrib import admin
from django.urls import path, include
from base import views as base_views
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #include the base url
    path('', include('base.urls')),
    #include the user page url
    path('users/', include('user.urls')),  

    #profile 
    path('profile/', user_views.profile, name = "profile"),
    path('profile/update/', user_views.update_profile, name = "update_profile")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
# base/urls.py

# Import necessary modules from Django
from django.urls import path
from . import views

# Namespace for the app, used to distinguish URLs within this app
app_name = 'base'

# Defining URL patterns for this app
urlpatterns = [
  # URL for the home page, mapped to the home view
  path('', views.home, name="home"),  
  
  # URL for displaying the list of questions, mapped to the QuestionListView
  path('questions/', views.QuestionListView.as_view(), name="question_list"), 
  
  # URL for creating a new question, mapped to the QuestionCreateView
  path('questions/new', views.QuestionCreateView.as_view(), name="question_create"),
  
  # URL for viewing details of a single question, mapped to the QuestionDetailView
  # The <int:pk> part captures the primary key of the question and passes it to the view
  path('questions/<int:pk>', views.QuestionDetailView.as_view(), name="question_detail"),

  # updating a question
  path('questions/<int:pk>/edit', views.QuestionUpdateView.as_view(), name="question_update"),

  # deleting the quesiton
  path('questions/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete'),

  #voting urls
  path('upvote_question/<int:question_id>/', views.upvote_question, name='upvote_question'),
  path('downvote_question/<int:question_id>/', views.downvote_question, name='downvote_question'),
  path('upvote_reply/<int:reply_id>/', views.upvote_reply, name='upvote_reply'),
  path('downvote_reply/<int:reply_id>/', views.downvote_reply, name='downvote_reply'),

 

]

user/urls.py
# user/urls.py

# Import necessary Django modules and views for routing
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views  # Importing Django's built-in authentication views
from .views import CustomLoginView  # Import custom views for login, register, and logout

# Define the app name to set the namespace for reverse lookups


# URL patterns that define the routing for various user-related pages
urlpatterns = [
  path('', views.home, name="home"),
  path('register/', views.register, name='register'),
  path('login/', CustomLoginView.as_view(), name='login'),
  path('logout/', views.logout_view, name='logout'),
  path('profile/<str:username>/', views.profile, name='profile'),
  path('users/', views.list_users, name='list_users'),
]

user/models.py
# user/models.py

# Import necessary modules for model creation and image handling
from django.db import models  
from django.contrib.auth.models import User  
from PIL import Image  

# Define the Profile model to extend the User model with additional user-specific data
class Profile(models.Model):
  # Define a one-to-one relationship between the Profile and User model
  # Each user has one profile, and the profile is deleted if the user is deleted
  user = models.OneToOneField(User, on_delete=models.CASCADE)  

  # Define the bio field to store a short description about the user
  bio = models.CharField(max_length=1000, default="")  

  # Define the email field to store the user's email address
  email = models.EmailField(default="")  

  # Define the image field to store the user's profile image
  # Default image is set, and uploads go to 'profile_pic' directory
  image = models.ImageField(default="profile_pic/default.jpg", upload_to="profile_pic")  

  # String representation of the profile, showing the username of the associated user
  def __str__(self):
    return f'{self.user.username} - Profile'

  # Override the save method to handle image resizing
  def save(self, *args, **kwargs):
    # Call the parent class's save method to first save the profile data
    super().save(*args, **kwargs)

    # Open the image using PIL to check its dimensions
    img = Image.open(self.image.path)

    # If the image is larger than 300x300, resize it to fit within those dimensions
    if img.height > 300 or img.width > 300:
      # Define the maximum output size as a tuple (300, 300)
      output_size = (300, 300)  
      # Resize the image while maintaining aspect ratio
      img.thumbnail(output_size)  
      # Save the resized image back to the same path
      img.save(self.image.path)  

user/forms.py
# user/forms.py

# Import necessary Django modules for form creation
from django import forms 
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm  
from django.db import models 
from .models import Profile 

# User registration form that inherits from Django's UserCreationForm
class UserRegisterForm(UserCreationForm):
  first_name = forms.CharField(max_length=200, required=True)
  last_name = forms.CharField(max_length=200, required=True)
  email = forms.EmailField(required=True)

  class Meta:
    model = User
    fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

  def save(self, commit=True):
    user = super().save(commit=False)
    if commit:
      user.set_password(self.cleaned_data['password1'])
      user.save()
    return user

# User update form for updating existing user information
class UserUpdateForm(forms.ModelForm):
  # Email field for updating the email
  email = forms.EmailField()

  class Meta:
    model = User  
    # Fields to display in the form
    fields = ['username', 'first_name', 'last_name', 'email']  

# Profile update form for updating user profile-related information
class ProfileUpdateForm(forms.ModelForm):
  class Meta:
    model = Profile  
    # Specify fields to include in the profile update form
    fields = ['bio', 'image']  

user/views.py
# user/views.py

# Import necessary classes and functions from Django for handling user authentication
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import logout
from django.contrib import messages
from .forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.decorators import login_required
from base.models import Question, Reply
from django.contrib.auth.models import User

# Custom LoginView to handle login with a custom template and prevent logged-in users from accessing the login page


class CustomLoginView(LoginView):
    """
    Custom login view to specify the template used for the login page.
    If the user is already authenticated, they will be redirected to the home page.
    """

    # Specify the template to be used for the login page
    template_name = 'users/login.html'

    def dispatch(self, request, *args, **kwargs):
        """
        Override the dispatch method to check if the user is authenticated.
        If authenticated, redirect to the home page.
        """

        # If the user is already logged in, redirect to home
        if request.user.is_authenticated:
            # Redirect to home page if the user is already logged in
            return redirect('home')

        return super().dispatch(request, *args, **kwargs)

# Home view function to render the homepage


def home(request):
    """
    Renders the home page.
    """
    return render(request, 'home.html')


def register(request):
    """
    Handles user registration. If the user is already logged in, redirect to the home page.
    If the request method is POST, it processes the registration form.
    """
    if request.user.is_authenticated:
        return redirect('home')  # Redirect if already logged in

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()  # Save the new user
            messages.success(
                request, 'Your account has been created! You can now log in.')
            # Use the user namespace for the login view
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form})

# Logout view to log the user out and redirect them to the homepage
# We could use a logout button in HTML since Django’s LogoutView requires a POST request for security reasons.


def logout_view(request):
    """
    Logs out the user and redirects them to the home page.
    """

    # Logout the user
    logout(request)
    # Redirect to home page after logging out
    return redirect('home')

# Profile view that requires the user to be logged in to access


@login_required
def profile(request, username):
    """
    Renders the profile page for the specified user.
    """
    # Get the user by the username or return a 404 error
    profile_user = get_object_or_404(User, username=username)

    # Fetch all questions posted by the user
    user_questions = Question.objects.filter(user=profile_user)

    # Fetch all questions the user has replied to
    replied_questions = Reply.objects.filter(
        user=profile_user).values('question').distinct()
    replied_question_ids = [reply['question'] for reply in replied_questions]
    replied_questions = Question.objects.filter(id__in=replied_question_ids)

    # Pass the data to the template
    return render(request, 'users/profile.html', {
        'profile_user': profile_user,
        'questions': user_questions,
        'replied_questions': replied_questions,
    })


# Update profile view to allow logged-in users to update their profile information
@login_required
def update_profile(request):
    """
    Allows logged-in users to update their profile and personal information.
    If the form is valid, the changes are saved and the user is redirected to their profile page.
    """

    # If the request method is POST, process the submitted data
    if request.method == 'POST':
        # Instantiate user and profile update forms with the submitted data
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)

        # If both forms are valid, save the data
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()  # Save the user form
            p_form.save()  # Save the profile form
            messages.success(
                request, 'Your profile has been updated successfully!')
            # Redirect to profile page after successful update
            return redirect('profile')
    else:
        # If it's a GET request, pre-populate the forms with the current user and profile data
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    # Prepare context to pass to the template for rendering
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    # Render the update profile page with the context data
    return render(request, 'users/update_profile.html', context)

# lists all the under of the webpage


def list_users(request):
    """
    View to display all active users who have not been deleted.
    Users are displayed as clickable cards/buttons with their profile pictures.
    Clicking on a user's name takes you to their profile page.
    """
    # Filter only active users (exclude deleted users)
    # Django sets `is_active` to False for deleted users.
    active_users = User.objects.filter(is_active=True)

    # Pass active users to the template
    return render(request, 'users/list_users.html', {'users': active_users})

user/templates/users/list_users.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'user/css/list_users.css' %}"> <!-- Link the CSS file -->
<div class="container">
    <h1>All Users</h1>
    <div class="user-list">
        {% for user in users %}
        <div class="user-card">
            <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="profile-pic">
            <h3><a href="{% url 'profile' user.username %}">{{ user.username }}</a></h3>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

user/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static 'css/auth.css' %}">
  <title>Login</title>
</head>
<body>
  <h2>Login to Theorem Talk</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
</body>
</html>

user/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'user/css/profile.css' %}"> <!-- Link the CSS file -->
<div class="profile">
  <h1>{{ profile_user.username|title }}'s Profile</h1>
  <img src="{{ profile_user.profile.image.url }}" alt="{{ profile_user.username }}" class="profile-pic">
  <p><strong>Bio:</strong> {{ profile_user.profile.bio }}</p>
  <p><strong>Email:</strong> {{ profile_user.email }}</p>

  <h3>Questions Asked:</h3>
  {% if questions %}
    <ul>
      {% for question in questions %}
        <li>
          <a href="{% url 'base:question_detail' question.id %}">{{ question.title }}</a>
        </li>
        <!-- Delet the question -->
        <div class="delete-question">
          {% if question.user == user %}
            <a href="{% url 'base:question_delete' question.pk %}" class="btn btn-danger">Delete Question</a>
          {% endif %}
        </div>

        <!-- Add button to go to the question update form -->
        {% if question.user == user %}
          <a href="{% url 'base:question_update' question.id %}">
            <button>Update Your Question</button>
          </a>
        {% endif %}
      {% endfor %}
    </ul>
    {% else %}
    <p>This user has not asked any questions yet.</p>
  {% endif %}

  <h3>Questions Replied To:</h3>
  {% if replied_questions %}
  <ul>
    {% for question in replied_questions %}
    <li>
      <a href="{% url 'base:question_detail' question.id %}">{{ question.title }}</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>This user has not replied to any questions yet.</p>
  {% endif %}
</div>

{% endblock %}

user/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static 'css/auth.css' %}">
  <title>Register</title>
</head>
<body>
  <h2>Register for Theorem Talk</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
  <p>Already have an account? <a href="{% url 'login' %}">Log in</a></p>
</body>
</html>

user/templates/users/update_profile.html
{% extends "base.html" %}
{% block content %}
<h2>Update Profile</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <h3>Update Account Details</h3>
        {{ u_form.as_p }}
    </div>
    <div>
        <h3>Update Profile</h3>
        {{ p_form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>
{% endblock %}